### ISSUE TITLE
underground parking should not be rendered

### ISSUE THREAD

**Issue by ecatmur** [oobrien/oomap#1]
For example, Goodman's Fields, SE of Aldgate East has amenity=parking parking=underground

**Comment by oobrien** [comment]
The parking key (as opposed to the tag amenity=parking) is not currently pulled in using the default.style file for osm2pgsql so implementing this will be harder than a simple update to the appropriate Mapnik style files, as it would require a database table reconfig and rebuild. This functionality will therefore be implemented once the parking key is included in https://github.com/openstreetmap/osm2pgsql/blob/master/default.style
