### ISSUE TITLE
Print map code on the map

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#13]
In lieu of a login based system, this will allow easier access to existing maps.

**Comment by rugk** [comment]
I think this is already done in the latest version, is not it?

**Comment by oobrien** [comment]
@rugk Correct that went in a few days back although I haven't yet committed the code in - that will go in with a bunch of other fixes I'm planning to do shortly.

**Comment by oobrien** [comment]
Now fixed and commited.
