### ISSUE TITLE
Include course details in PDF

### ISSUE THREAD

**Issue by Maprunner** [oobrien/oomap#24]
The worldfile and JPG updates (issue #6) make integration with RG2 a lot simpler. The next step would be to include the course details as metadata somehow. Given that RG2 will use the jpg file it might be possible to add EXIF data for control details (and possibly georeferencing as well, which would remove the need for the worldfile). This would then allow RG2 to be updated to automatically calculate scores for uploaded GPX files for an OOM event.

If it is easier you could add metadata to the PDF and I could implement a PDF map option in RG2.

**Comment by oobrien** [comment]
If you can specify a format or metadata API for this, then I will be happy to implement. For now, the data is included as micro-text on the bottom left of each PDF. Each control has four sections - WebMercator lat, WebMercator lon, control number and label angle. Start/Finish and Xs don't have the latter two.

**Comment by oobrien** [comment]
Course information now included in the KML download.
