### ISSUE TITLE
Render objects tourism=information/information=board

### ISSUE THREAD

**Issue by rugk** [oobrien/oomap#27]
Followup of https://github.com/oobrien/oomap/issues/25. You may also render these objects as special items:
* tourism=information/information=board
* emergency=fire_hydrant/fire_hydrant:type=pillar (preferably as a blue cross as it is a "water object")

Also:
* What about `barrier=gate`?
* `man_made=tower`

**Comment by cadnant** [comment]
man_made=tower added.
To avoid clutter, the other suggestions will remain unrendered.
