### ISSUE TITLE
Claims plaques are not available (in Germany)

### ISSUE THREAD

**Issue by rugk** [oobrien/oomap#28]
In Germany the application claims the plaques are not available:
> Unfortunately local plaques could not be retrieved. An error occurred.
>
> There  are no plaques in this area recorded on the Open Plaques database, or a  system error is preventing retrieval of plaques for this area. Open  Plaques has a high number of plaques in the UK, USA and Germany. Check  the Open Plaques website at http://openplaques.org/places/

 I also see that the request to `http://oomap.co.uk/getopenplaques.php` returns an "empty" result, so it does not seem to be a bug there.

I even tested it in the middle of Berlin and [in OpemPlaques.org](http://openplaques.org/places/de/areas/berlin/plaques) there is more than enough data.

**Comment by oobrien** [comment]
Plaques are coming in fine for me, in central Berlin, so there may have just been a temporary glitch on the OpenPlaques server. Please can you check again? If they are still failing for you, please me know your setup (browser version, OS, anything unusual).

**Comment by oobrien** [comment]
OpenPlaques coverage is concentrated in UK, US and DE cities - see http://openplaques.org/places - if you find a plaque that is on OpenPlaques but not OOM please let me know and reopen this bug. There could still be an issue, e.g. mis-parsing of quotes/dashes, that could cause them to not load into OOM, but I can't find any now. Tested it's working in London, Cambridge, Berlin and Washington DC.
