### ISSUE TITLE
Selecting single item for move / delete

### ISSUE THREAD

**Issue by IanDitchfield** [oobrien/oomap#3]
It would be nice to be able to select a control and move it. At present, it is only possible to delete a control and then re-create it in a different place.

**Comment by oobrien** [comment]
This is by design, to keep the UI as simple as possible - but I agree this would be nice to have.

**Comment by cadnant** [comment]
Addressed in #73 .  All overlay points (controls, S, F, crossings, 'X') can be moved by dragging on the map.  They can also be edited by double-clicking.
