### ISSUE TITLE
Some trees appearing above black lines, and some below it.

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#35]
(seen in PDF of the oterrain style in the Global edition, at least)

<img width="290" alt="screen shot 2018-08-13 at 12 56 21" src="https://user-images.githubusercontent.com/6453188/44030325-5f586e44-9ef8-11e8-8dec-7d66ac96fa09.png">

**Comment by oobrien** [comment]
Location of the above on OSM is https://www.openstreetmap.org/#map=19/38.25248/-85.75160

**Comment by cadnant** [comment]
Does applying the darken operation at the style level instead of the rule level help?
```
<Style name="symbols" comp-op="darken">
```

**Comment by cadnant** [comment]
Think this is now fixed - certainly consistent, even if not fully ISOM-compliant:
![image](https://user-images.githubusercontent.com/61116747/226198671-3027e0bf-a43e-43c9-b4bd-596f7a662ecc.png)
