### ISSUE TITLE
Course export to IOF XML/KML

### ISSUE THREAD

**Issue by davidcurrie** [oobrien/oomap#39]
Looking to use OOMap with [MapRun](http://maprunners.weebly.com/). As inputs, it takes a KMZ for the map and either a KML file or IOF XML 2.0.3 for the course. Conversion of a base map from the OOMap PDF or JPG is easy enough (although bonus points for a KMZ export too!). What's less easy is re-using a course planned on OOMap hence the request for an IOF XML/KML export option.

**Comment by davidcurrie** [comment]
I notice from #24 that the course is encoded in the PDF so, in theory, I should be able to extract it from there...

**Comment by oobrien** [comment]
Hi David - it is! But probably easier for me to generate it. If you can point me to the documentation then I'll see if I can put it together.

**Comment by davidcurrie** [comment]
Thanks Ollie. Here's the description of what MapRun is expecting:
http://maprunners.weebly.com/uploads/6/8/6/6/6866500/technical_overview_-_extract_-_file_formats_v1.pdf

The following describes the process currently used to generate the KMZ from various sources, including OOMap:
http://maprunners.weebly.com/maps---kmz-files.html

And for generating the KML using Google Earth:
http://maprunners.weebly.com/course-setting.html

**Comment by oobrien** [comment]
KML course export now live.

Working on KMZ map export.

**Comment by davidcurrie** [comment]
Sorry @oobrien - only just seen this as the GitHub notification got buried in amongst those from work. Just taken this for a spin and it works a treat! There's a warning about the KMZ not being tiled but I'm not sure what the implications of that are - I'll check with Peter. I know on iOS the size of the KMZ can be an issue but I believe you're well below that.

**Comment by davidcurrie** [comment]
FWIW: Peter responded that the lack of tiling shouldn't be a problem with MapRunF so I think we can consider this closed. Thanks again @oobrien!

**Comment by oobrien** [comment]
@davidcurrie Sorry for tardy reply. Yes, my simple code doesn't tile, it just uses a double-resolution JPG and uses it as is. MapRunF I believe has a file size limit of 1.5MB to manage memory resources efficiently, and so prefers tiled images. Most if not all OOM JPGs should be below 1.5MB though. In the rare case that they are not there is a converter at http://www.p.fne.com.au/ that will tile them up.

**Comment by davidcurrie** [comment]
Cheers @oobrien. I seem to recall that the size was generally only ever an issue on iOS so, speaking selfishly, not a problem! Thanks once again for all the good work!
