### ISSUE TITLE
Move/delete red cross

### ISSUE THREAD

**Issue by IanDitchfield** [oobrien/oomap#4]
Even more useful would be the ability to select and move or delete a single red cross. At present, if you want to move a red cross, the only option available is to delete the every red cross and start again.
(Actually, there's no real need for a move function. Just the ability to delete a specified red cross would do; easy enough to create a new one).

**Comment by cadnant** [comment]
Addressed in #73 .  All overlay points (controls, S, F, crossings, 'X') can be independently moved by dragging on the map.  They can also each be edited (including deletion), by double-clicking.
