### ISSUE TITLE
Rendering of Gardens mapped as private

### ISSUE THREAD

**Issue by SK53** [oobrien/oomap#40]
Hi Ollie,

We've just had a new contributor [delete masses of stuff](https://www.openstreetmap.org/changeset/78111129#map=14/52.5375/-1.7987) around Birmingham because they didn't like how OOmap had rendered them. 

I have no idea if this is relevant to what you intend with oomap (looking at areas I know, there is no distinction between accessible & private areas of countryside, so I suspect not). So, this if this is not in scope, then please feel free to close the issue, but if it is (e.g., gardens+private = urban) then all to the good too.

Regards,

Jerry

**Comment by oobrien** [comment]
Hi @SK53, yes I have just got an email from them too. I probably need to add a note on OOM about this - we of course encourage additions, but deletions of things that still exist on the ground are not good. I presume you can roll the changeset back? 

I'll keep this open as yes, I need to make rendering changes on OOM to not show leisure=garden closed ways as open space and not render fences from closed ways which are barrier=fence and leisure=garden.

**Comment by SK53** [comment]
Thanks. Yes, the changeset was reverted: https://www.openstreetmap.org/changeset/78166466.
