### ISSUE TITLE
Mention in starting popup that it is open source

### ISSUE THREAD

**Issue by westnordost** [oobrien/oomap#42]
Until I found the link to this repository, I thought that the openorienteeringmap is not open source. The link is only mentioned somewhere in the blog, but not in the about-popup that comes up when opening the page.

I think it is a big pro that it is open source, thank you for this, and should be mentioned more prominently.

I wanted to link to oomap from an open source OpenStreetMap related app because of its great utility, but wasn't sure if I should do it because I thought it isn't open source. Now that I discovered this, I am reassured.

**Comment by westnordost** [comment]
(Also, is there an icon for the open orienteering map?)

**Comment by rugk** [comment]
Though is this really useful for the general public (i.e. StreetComplete users) and not only those, interesting in [orienteering sports](https://en.wikipedia.org/wiki/Orienteering)?

**Comment by cadnant** [comment]
Fixed in #62
