### ISSUE TITLE
KMZ of map (without course) for MapRunF export

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#46]

**Comment by jcundill** [comment]
In doc.kml of the generated kmz file I needed to change the LatLonBox rotation to  0.0 to get the kmz to upload via the MapRunF checksites page

https://github.com/oobrien/oomap/blob/23ecc5998a0d6f345548bc9c1062e5248605704c/maptiler/www/handleKMZ.py#L118

**Comment by oobrien** [comment]
@jcundill I believe the issue is how the zip utility in python is zipping the files, compared with how you would manually zip them. Unzipping and rezipping outside of python should fix the issue. I'm looking to try and get the python zipping working correctly.

**Comment by jcundill** [comment]
@oobrien, thanks you are right - just rezipping the generated kmz fixes it.

**Comment by oobrien** [comment]
@jcundill I have now fixed this issue in https://github.com/oobrien/oomap/commit/0097c1d5a6dfd424151f944f892277e764457cbc (the zipping code was not marking the doc.kml explicitly as a file so MapRunF was treating it as a folder, plus MapRunF was fussy about the name of the image) and have reenabled the button on https://oomap.co.uk/gb/
