### ISSUE TITLE
A4 map comes out scaled to A2

### ISSUE THREAD

**Issue by cadnant** [oobrien/oomap#48]
PDF generation results in the correct map area, but incorrectly scaled - an A4 request generates a 16.54 x 23.39 inch PDF.  Workaround - rescale PDF on printing.

**Comment by davechaffey** [comment]
I have found this also - the JGW now seems to scale A4 to A2 in Google Earth

**Comment by cadnant** [comment]
Hi Ollie,

Tested (briefly) and confirmed fixed - many thanks for the quick resolution.

Thanks too for fixing the postbox problem - we're currently running a 
lockdown-friendly challenge around postboxes so that was a bit of an 
issue!  We've noticed that the Dracos DB is increasingly out of date, so 
- at some stage - I wonder if it makes sense to switch to the OSM data 
as a source for postboxes? Certainly it's more accurate locally, but I'm 
sure that's not true everywhere.

Cheers,

David (cadnant)

**Comment by oobrien** [comment]
@cadnant Thanks, yes I didn't realise it was not being sync'd with OSM - the issue though is that many postboxes on the project don't have the corresponding data on OSM - they were added directly to the Dracos project.

**Comment by oobrien** [comment]
@cadnant But I could add in an additional pull from OSM via say the Overpass API. I'll add it as an "issue" here.

**Comment by davechaffey** [comment]
No worries Ollie - thank you for the update.

Unfortunately, I think the PDF/JPG/JGW created is now too small for the area required. Note I'm a novice at using OOMap and MapRun Utils so I'm not a reliable datapoint. The Direct Save to KMZ does load to MapRun at the required scale 1:5000 (great feature for all lockdown maps we're creating thanks) although I got a warning that it was untiled. 

However, when I save to JPG/JPW and put them through the utility "Create a KMZ file (with 512x512 tiles) from a jpg and jgw file" http://www.p.fne.com.au/rg/cgi-bin/o-utils.cgi?act=manager&keksi= a smaller map is produced than required as shown top left 

HTH, Dave

**Comment by oobrien** [comment]
Thanks, hmm, that sounds like the JGW file is incorrect now. I'll have a look...

**Comment by oobrien** [comment]
@davechaffey I'm unable to reproduce this, both by putting the JPG/JGW in QGIS and by using the tool you linked above and putting it in Google Earth. It is possible that the tool had been reconfigured to counteract the scale doubling issue, and has now been configured back. Could you check again with a new map, or by resaving your current one (load it in, save, then once the PDF is downloaded, download the JPGs and JGWs)?

**Comment by davechaffey** [comment]
Confirm scales correctly for me with new map @oobrien - when I started a new map/reloaded browser. Thanks.
