### ISSUE TITLE
Postboxes not being added

### ISSUE THREAD

**Issue by Maprunner** [oobrien/oomap#49]
"Add postboxes" stopped working some time after Tuesday this week. Reproducible in St Albans and central London at least.

Function handleGetPostboxesCallback is getting a null input which generates a TypeError in the console.

**Comment by cadnant** [comment]
File moved at dracos.co.uk?
Missing:
http://dracos.co.uk/made/nearest-postbox/nearest.php
Looks like its now:
https://postboxes.dracos.co.uk/nearest.php
Therefore update needed in:
www/oomap.co.uk/gb/getpostboxes.php
