### ISSUE TITLE
Trees scale wrong

### ISSUE THREAD

**Issue by HTMLSniper** [oobrien/oomap#5]
In the global edition with PseudO at 15k or higher scale, the trees and farmland and some thickets are way to big in the exported pdf. Trees are bigger than everything else lol.

**Comment by cmgers01** [comment]
I believe I'm having the same issue

**Comment by oobrien** [comment]
Thanks both, I'm looking into this issue.

**Comment by cmgers01** [comment]
Any luck turning off the trees?

Unfortunately for me it looks to be some overachieving open street mapper decided to pepper my city’s downtown with every single tree.
