### ISSUE TITLE
Knock out buildings in parks etc on Street_O render

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#59]
Use http://mapnik.org/mapnik-reference/#3.0.22/polygon-comp-op to substract bulidings from parks.

**Comment by cadnant** [comment]
...or render in white on top?  cadnant/oomap@659bac63cb698f4bc9da69a2ecc7caa82bec4a80

**Comment by cadnant** [comment]
Addressed in #69 and enhanced in later commits.  For Street-O style, any buildings overlapping an area rendered in colour are identified and rendered as white on top.  Non-overlapping buildings are ignored.
