### ISSUE TITLE
Don't show access=no footpaths

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#61]
"I’ve noticed that private and access=no footpaths are being rendered in Open Orienteering Map, but I don’t think they should be. I expect most planners won’t manually check every path on the ground before using OOM, so in my opinion, anything marked on the map should be publicly accessible. For example, there is a path across the field in The Judd School, Tonbridge, which I can assure you is strictly OOB and is tagged access=private. Do you have a good reason for showing private paths? If not, could you remove any private paths/tracks/roads please? As ever with OSM, it’s tricky to know which values of access to permit, but I think hiding anything with attributes access=no or access=private or not(foot is set and (foot=no or foot=private)) is a good place to start. In case you don’t have it to hand, https://wiki.openstreetmap.org/wiki/Key:access has a comprehensive list."

**Comment by oobrien** [comment]
Yes, I agree with you. Generally I would allow access=no/private roads because often these are passible by foot even if the tagging is not that granular.
However I would agree that I shouldn’t be mapping access=no footways/paths because paths are specifically for use on foot so the tagging will be thinking about that.

**Comment by cadnant** [comment]
Private or "access=no" footways are not rendered on the Streeto or Pseudo styles.
