### ISSUE TITLE
Memory issues with graveyard_overprint style rule

### ISSUE THREAD

**Issue by hholzgra** [oobrien/oomap#63]
While adding the oomap styles to my MapOSMAtic instance, I found that the OTerrain style exhausted all memory while processing the graveyard_overprint style, even when commenting out the transformation part of the PolygonPatternSymbolizer, when rendering as PNG using the Mapnik CairoGraphics backend. SVG output on the other hand was generated without any issue ...

Not sure whether this is a Mapnik bug after all, but so far the only styles I had this happening with were the "Pencil" and "Space Station" styles due to their massive use of pattern textures, and only at larger paper sizes, while here the problem already occurs with DinA4 (at 300dpi, so generating a 
3500x2500 pixel PNG)

**Comment by cadnant** [comment]
Not really an issue with oomap but regardless, the png icon that presumably causes the problems has previously been removed from the rendering.
