### ISSUE TITLE
Rendering of OSM's leisure=sports_centre

### ISSUE THREAD

**Issue by Choreuomai** [oobrien/oomap#66]
Hi,
OSM's leisure=sports_centre tag is rendered as a building (black) in PseudO style (as seen at https://oomap.co.uk/global/#/new/oterrain_global/17/10.9366/52.4113/). It shouldn't, because the OSM tag doesn't per se imply it's a building. There are also outdoor sports centres, as in the referenced case. It should only be rendered as a building if there's also a building=* tag in addition to leisure=sports_centre.

**Comment by cadnant** [comment]
This got fixed somewhere along the line:
![image](https://user-images.githubusercontent.com/61116747/226199187-66e3e71a-e68e-431c-8ade-8cc1a807c716.png)

See https://tile.dna-software.co.uk/render/pdf/?style=oterrain-NONE-0|paper=0.297,0.210|scale=5000|centre=6874922,1216743|title=OpenOrienteeringMap|eventdate=|club=none|id=6417555e0de79|start=|finish=|crosses=|cps=|controls=|rotation=-0.0711|grid=yes|rail=yes|walls=yes|trees=yes|hedges=yes|drives=no|fences=yes|linear=no|dpi=150
