### ISSUE TITLE
URL parameters for the map PDF download - use & not |

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#71]
Join the rest of the world in using & rather than | as my URL parameters, because some email clients will URL encode | as %27, which is perfectly valid but breaks my renderer.

Or convert %27 to | when parsing the URL string in the renderer

**Comment by cadnant** [comment]
Although "|" is still used, URL-encoding is accepted by the renderer and "&" will also work if used.  Therefore consider this fixed.
