### ISSUE TITLE
Remove walls from the street-O layers

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#75]
They are not so useful, as they look like roads, and in some places, every garden has a set of walls mapped around it - not so useful.

e.g. Jericho in Oxford.

**Comment by cadnant** [comment]
Fixed already? [Walls (and other features) selectable through rendering options dialog](https://github.com/oobrien/oomap/commit/c8f8f1be0df6081ef797c32fb0215fee1c56ba08).

**Comment by oobrien** [comment]
@cadnant Good point. This changes was for my old deployment but I realise that is now quite out of sync with this and I really need to work on a branch. I will revert!

**Comment by cadnant** [comment]
Fixed in #69 - rendering of walls (and other features) selectable through "Rendering options" button.
