### ISSUE TITLE
Don't show natural=scree

### ISSUE THREAD

**Issue by ravenfeld** [oobrien/oomap#77]
Hello, I just discovered your work which is top. Thanks again.

I would like to warn you that for the moment some surfaces are not precise in account.

natural=scree

I don't know if your tool can replace software like OCAD but with the strength of OSM I think it can.

**Comment by ravenfeld** [comment]
I found this: https://wiki.openstreetmap.org/wiki/IOF_mapping

Does all the mapping exist on your rendering?

**Comment by cadnant** [comment]
oomap was originally written to support urban events so many non-urban features are not rendered. However it's certainly possible to add in a new area type so will keep this open.  Assume mapping as something like ISOM 210 (stony ground, slow running; https://omapwiki.orienteering.sport/symbols/210-stony-ground-slow-running/ ) would be appropriate?

**Comment by ravenfeld** [comment]
A ok, I understand better now why also ruined walls and ruined fences are not taken into account. 

[wiki.openstreetmap.org/wiki/IOF_mapping](https://wiki.openstreetmap.org/wiki/IOF_mapping)

On the wiki mapping I have the impression that they made everything match and for natural=screen it is well 210 for them.

**Comment by cadnant** [comment]
Scree is now rendered in the PseudO style.
