### ISSUE TITLE
Export possibilities to Open Orienteering Mapper

### ISSUE THREAD

**Issue by ratzupaltuff** [oobrien/oomap#79]
Hi, I am new to making orienteering maps. I really like this map creation tool. But I found some errors on the created output in my region. Namely two layer areas and areas that were mapped as private area but arenˋt. 

I would like to edit these mistakes without redrawing the whole map with open orienteering mapper. 
My current approach is to extract the svg from the generated pdf and edit that with inkscape. But it would be nicer for some more complex symbols to edit the map in open orienteering mapper. Is there any way to import the map there? The only way I found to import the pdf/svg converts the image to pixels and then you can‘t edit the map in oomapper. 

I would appreciate any hints for a better workflow. How do you edit the generated Map?

**Comment by cadnant** [comment]
Hi - my current workflow is very similar to yours - for alterations that aren't appropriate for direct incorporation into the Openstreetmap database, I import into Inkscape and add/edit elements there.

To get data into open orienteering mapper, you are probably better off importing the openstreetmap data directly (eg. using the Overpass API - one example at https://overpass-turbo.eu/).

For your particular example of non-private areas marked as out of bounds: building sites, landfill sites and schools are marked as OOB (purple).  One option would be to make this optional - do you have an example map ID so I can have a look?
