### ISSUE TITLE
Make Oomap compatible with Vikazimut

### ISSUE THREAD

**Issue by cadnant** [oobrien/oomap#84]
1.  check XML 3.0 export is compatible - change expectations at either Oomap or Vikazimut end as needed.
2. Provide option to add course to jpg in .KMZ file

**Comment by cadnant** [comment]
FYI @Eric-P-Kmz

**Comment by Eric-P-Kmz** [comment]
1. Regarding XML compatibility : Vikazimut's XML uses a tag <Map>that contains several pieces of information. In particular, the map scale value is mandatory, so it's possible to add the following tag to your XML <RaceCourseData><MAP><Scale> map scale </Scale></Map></RaceCourseData>
2. KMZ compatibility : vikazimut use the course map (map+circles+...). Currently, the KMZ contains the jpeg of the map.

**Comment by cadnant** [comment]
Map scale added to XML export.
Option (in "Rendering Options" dialog) to "Show course on kmz export" [turned off by default].

Both changes ready for testing on the https://oomap.ptlnet.com/ instance only - @Eric-P-Kmz please see if these now work for Vikazimut; if so I'll release to the main instance.

**Comment by Eric-P-Kmz** [comment]
Hi,

Nice, it works.

Would it be possible to have a simple Vikazimut button that would trigger the download of the Kmz file with the 200 dpi route map and the new XML ? (150 dpi is too low resolution for phones and 300 dpi gives maps that are too big)
This would greatly simplify the task for novice users.

I'm planning to make a video about this feature on your site, as well as a video about georeferencing IOF jpeg maps for teachers. Any objections?

**Comment by cadnant** [comment]
Glad that works - now active across both servers.
I don't want to complicate the interface too much more so let's see how it goes with it as-is (and having to remember to update the 2 settings).
Video - no problem - thanks!
