### ISSUE TITLE
LONG BLACK line

### ISSUE THREAD

**Issue by POTTERIES** [oobrien/oomap#9]
There is a long black line passing through Stoke on trent .... I have been reliably told goes to Ulapool.
Not on OSM .

**Comment by oobrien** [comment]
This may have been a bad edit on the OSM master database. It looks like it is resolved, as I cannot see a line passing through Stoke-on-Trent now. The database is synced daily with the master one, so it looks like the edit there has been fixed/reverted and the fix has fed through.
